name 'code_generator'
maintainer 'David Echols'
maintainer_email 'dhechols@gmail.com'
license 'Apache2'
description 'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version '1.0.0'
